# generated by datamodel-codegen:
#   filename:  ddependency-check-report.json
#   timestamp: 2025-12-13T18:37:45+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class DataSourceItem(BaseModel):
    name: str
    timestamp: str


class ScanInfo(BaseModel):
    engineVersion: str
    dataSource: List[DataSourceItem]


class Credits(BaseModel):
    NVD: str
    CISA: str
    NPM: str
    RETIREJS: str
    OSSINDEX: str


class ProjectInfo(BaseModel):
    name: str
    reportDate: str
    credits: Credits


class PackageId(BaseModel):
    id: str


class RelatedDependency(BaseModel):
    isVirtual: bool
    fileName: str
    filePath: str
    sha256: Optional[str] = None
    sha1: Optional[str] = None
    md5: Optional[str] = None
    packageIds: Optional[List[PackageId]] = None


class VendorEvidenceItem(BaseModel):
    type: str
    confidence: str
    source: str
    name: str
    value: str


class ProductEvidenceItem(BaseModel):
    type: str
    confidence: str
    source: str
    name: str
    value: str


class VersionEvidenceItem(BaseModel):
    type: str
    confidence: str
    source: str
    name: str
    value: str


class EvidenceCollected(BaseModel):
    vendorEvidence: List[VendorEvidenceItem]
    productEvidence: List[ProductEvidenceItem]
    versionEvidence: List[VersionEvidenceItem]


class Package(BaseModel):
    id: str
    confidence: str


class Cvssv3(BaseModel):
    baseScore: float
    attackVector: str
    attackComplexity: str
    privilegesRequired: str
    userInteraction: str
    scope: str
    confidentialityImpact: str
    integrityImpact: str
    availabilityImpact: str
    baseSeverity: str
    version: str
    exploitabilityScore: Optional[str] = None
    impactScore: Optional[str] = None


class Reference(BaseModel):
    source: str
    url: str
    name: Optional[str] = None


class Software(BaseModel):
    id: str
    vulnerabilityIdMatched: Optional[str] = None


class VulnerableSoftwareItem(BaseModel):
    software: Software


class Cvssv2(BaseModel):
    score: float
    accessVector: str
    accessComplexity: str
    authenticationr: str
    confidentialityImpact: str
    integrityImpact: str
    availabilityImpact: str
    severity: str
    version: str
    exploitabilityScore: str
    impactScore: str


class Vulnerability(BaseModel):
    source: str
    name: str
    unscored: Optional[str] = None
    severity: str
    cvssv3: Optional[Cvssv3] = None
    cwes: List[str]
    description: str
    notes: str
    references: List[Reference]
    vulnerableSoftware: List[VulnerableSoftwareItem]
    cvssv2: Optional[Cvssv2] = None


class VulnerabilityId(BaseModel):
    id: str
    confidence: str
    url: Optional[str] = None


class Dependency(BaseModel):
    isVirtual: bool
    fileName: str
    filePath: str
    md5: Optional[str] = None
    sha1: Optional[str] = None
    sha256: Optional[str] = None
    relatedDependencies: Optional[List[RelatedDependency]] = None
    evidenceCollected: EvidenceCollected
    license: Optional[str] = None
    projectReferences: Optional[List[str]] = None
    packages: Optional[List[Package]] = None
    description: Optional[str] = None
    vulnerabilities: Optional[List[Vulnerability]] = None
    vulnerabilityIds: Optional[List[VulnerabilityId]] = None

# by default generates as Model


class DCModel(BaseModel):
    reportSchema: str
    scanInfo: ScanInfo
    projectInfo: ProjectInfo
    dependencies: List[Dependency]
